name: ci

# Controls when the action will run. Triggers the workflow on push for any branch, and
# pull requests to master
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/yitzchak/archlinux-cl:latest
      options: --security-opt seccomp:unconfined
      
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm jupyterlab python-build

    - name: Install pytest-jupyter_kernel
      run: |
        git clone https://github.com/yitzchak/pytest-jupyter_kernel.git
        cd pytest-jupyter_kernel
        pyproject-build
        pip install --break-system-packages --user dist/pytest_jupyter_kernel-0.1.0-py3-none-any.whl

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Lisp Environment
      run: |
        make-rc
        asdf-add

    - name: Install CCL kernel
      run: |
        ccl --batch --load scripts/usr-install.lisp

    - name: Install CLASP kernel
      run: |
        clasp --non-interactive --load scripts/usr-install.lisp

    - name: Install ECL kernel
      run: |
        ecl --load scripts/usr-install.lisp --eval '(ext:quit)'

    - name: Install SBCL kernel
      run: |
        sbcl --non-interactive --load scripts/usr-install.lisp sbcl

    - name: Run kernel tests
      run: |
        pytest --verbose
